//! A hand-typed ROM address in a test's map TOML rots silently.
//!
//! `pins.rs` is regenerated by `repin` from the build's own listing, so a
//! region base that reads `pins::` cannot survive a cartridge re-layout in a
//! stale state. A base that is TYPED can, and the negative probes are where it
//! rots unseen: their assertions are `assert_ne!`-shaped ("the doctored compile
//! must NOT match"), which is satisfied at a stale base and at the true base
//! alike. Nothing goes red, and the probe quietly stops proving what its
//! comment claims.
//!
//! The rule this gate enforces is narrow enough to need no allowlist: a map
//! region named after a REAL gated cartridge region — a name `pins.rs` declares
//! a `Region` for — must take its `lma_base` from an expression, not a hex
//! literal. Synthetic toy regions (`probe`, `obj_bank`, `data`, `dac_bank`,
//! `text`) are untouched, because none of their names is a region pin.
//!
//! One legitimate shape does type a literal under a real region name: a test
//! that gates region A must still PLACE neighbouring region B somewhere for the
//! link to close, and parks it at an arbitrary harness-private address. Such a
//! site declares itself with a ``synthetic-carrier: `B` `` comment on the line or
//! just above it, naming the region it exempts in backticks. The marker is the
//! point — a bare literal cannot be told apart from a stale real base by reading
//! it, which is how the tranche probes' bases rotted unseen; a declared one can.
//! Naming the region is what keeps one marker from clearing a whole single-line
//! map TOML, second region included.
//!
//! Scope is every `crates/sigil-cli/tests/*.rs`, not one tranche: the property
//! is the boundary, not the filename.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn tests_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests")
}

fn pins_rs() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../sigil-harness/src/pins.rs")
}

/// Every region name `pins.rs` declares, lowercased into the spelling a map
/// TOML uses (`pub const ACT_DESCRIPTOR: Region` -> `act_descriptor`).
fn pinned_region_names() -> BTreeSet<String> {
    let src = std::fs::read_to_string(pins_rs())
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", pins_rs().display()));
    let mut out = BTreeSet::new();
    for line in src.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("pub const ") else {
            continue;
        };
        let Some((name, tail)) = rest.split_once(':') else {
            continue;
        };
        if tail.trim_start().starts_with("Region") {
            out.insert(name.trim().to_ascii_lowercase());
        }
    }
    out
}

/// Strip the Rust string-literal escaping a map TOML carries when it is written
/// inline (`name = \"core\"` -> `name = "core"`), so one scanner handles both
/// the escaped and raw spellings.
fn unescape(line: &str) -> String {
    line.replace("\\\"", "\"")
}

/// One `lma_base` assignment found in a test source, with the region name whose
/// block it belongs to.
struct BaseSite {
    file: String,
    line: usize,
    region: String,
    value: String,
    declared_carrier: bool,
}

/// The region names a `synthetic-carrier:` marker on this line exempts.
///
/// The marker must name its region in backticks, and it exempts ONLY that one.
/// A marker that exempted whatever sat near it would blanket-clear every region
/// on a single-line map TOML — which is precisely where a second, unnoticed base
/// hides.
fn carrier_exemptions(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut at = 0;
    while let Some(rel) = line[at..].find(CARRIER_MARKER) {
        let pos = at + rel + CARRIER_MARKER.len();
        at = pos;
        let rest = line[pos..].trim_start();
        let Some(rest) = rest.strip_prefix('`') else {
            continue;
        };
        let Some(end) = rest.find('`') else { continue };
        out.push(rest[..end].to_string());
    }
    out
}

/// One token the pairing cares about, in source order.
enum Tok {
    Name(String),
    Base(String),
}

/// Every `name = "X"` and `lma_base = V` on one line, in COLUMN order.
///
/// Per-line rather than per-file because a map TOML is frequently written as a
/// single inline string holding several `[[region]]` blocks — scanning only the
/// first match on such a line would pair region one's name with region one's
/// base and never see region two at all.
fn tokens(line: &str) -> Vec<(usize, Tok)> {
    let mut out = Vec::new();
    let mut at = 0;
    while let Some(rel) = line[at..].find("name = \"") {
        let pos = at + rel;
        let rest = &line[pos + "name = \"".len()..];
        match rest.find('"') {
            Some(end) => out.push((pos, Tok::Name(rest[..end].to_string()))),
            None => break,
        }
        at = pos + "name = \"".len();
    }
    let mut at = 0;
    while let Some(rel) = line[at..].find("lma_base") {
        let pos = at + rel;
        at = pos + "lma_base".len();
        let rest = &line[at..];
        let Some(eq) = rest.find('=') else { continue };
        let value: String = rest[eq + 1..]
            .trim_start()
            .chars()
            .take_while(|c| !c.is_whitespace() && *c != '\\' && *c != ',')
            .collect();
        out.push((pos, Tok::Base(value)));
    }
    out.sort_by_key(|(pos, _)| *pos);
    out
}

/// Walk a source file pairing each `lma_base` with the nearest `name = "X"`
/// before it. Map region blocks always spell the name first, so the most recent
/// name is the owning block — within a line as well as across lines.
fn scan(file: &Path) -> Vec<BaseSite> {
    let src = std::fs::read_to_string(file)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", file.display()));
    let short = file.file_name().unwrap().to_string_lossy().to_string();
    let lines: Vec<&str> = src.lines().collect();
    let mut current: Option<String> = None;
    let mut out = Vec::new();
    for (idx, raw) in lines.iter().enumerate() {
        let exempt: Vec<String> = std::iter::once(*raw)
            .chain(
                lines[idx.saturating_sub(CARRIER_LOOKBACK)..idx]
                    .iter()
                    .copied(),
            )
            .flat_map(carrier_exemptions)
            .collect();
        for (_, tok) in tokens(&unescape(raw)) {
            match tok {
                Tok::Name(n) => current = Some(n),
                Tok::Base(value) => {
                    if let Some(region) = current.clone() {
                        let declared_carrier = exempt.contains(&region);
                        out.push(BaseSite {
                            file: short.clone(),
                            line: idx + 1,
                            region,
                            value,
                            declared_carrier,
                        });
                    }
                }
            }
        }
    }
    out
}

/// The opt-out a neighbouring-region placement declares itself with. The region
/// it exempts follows it in backticks.
const CARRIER_MARKER: &str = "synthetic-carrier:";

/// How far above an `lma_base` the marker may sit. A map TOML is often one long
/// inline string, so the comment cannot go on the assignment's own line; a few
/// lines of lookback keeps it attached to the block it explains without letting
/// one marker cover an unrelated region elsewhere in the file.
const CARRIER_LOOKBACK: usize = 4;

fn is_hex_literal(v: &str) -> bool {
    let Some(digits) = v.strip_prefix("0x").or_else(|| v.strip_prefix("0X")) else {
        return false;
    };
    !digits.is_empty() && digits.chars().all(|c| c.is_ascii_hexdigit() || c == '_')
}

#[test]
fn real_region_map_bases_are_derived_never_hand_typed() {
    let pinned = pinned_region_names();
    // LOUD ON UNMEASURABLE: an empty authority list would make every check below
    // pass by finding nothing to check.
    assert!(
        pinned.len() > 50,
        "pins.rs must yield the region-name authority, got {} names, so the scan \
         below would silently check nothing",
        pinned.len()
    );

    let dir = tests_dir();
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "rs"))
        .collect();
    files.sort();
    // LOUD ON UNMEASURABLE: a broken glob must not read as a clean sweep.
    assert!(
        files.len() > 100,
        "expected the sigil-cli test corpus, found {} .rs files under {}",
        files.len(),
        dir.display()
    );

    let sites: Vec<BaseSite> = files.iter().flat_map(|f| scan(f)).collect();
    let real: Vec<&BaseSite> = sites
        .iter()
        .filter(|s| pinned.contains(&s.region))
        .collect();
    // LOUD ON UNMEASURABLE: if the block-pairing ever stops matching the house
    // map-TOML spelling, `real` empties out and the offender list below is empty
    // for the wrong reason.
    assert!(
        real.len() > 40,
        "the scanner paired only {} real-region map blocks, the map-TOML spelling \
         it keys on must have changed, so a hand-typed base could pass unseen",
        real.len()
    );

    let offenders: Vec<String> = real
        .iter()
        .filter(|s| is_hex_literal(&s.value) && !s.declared_carrier)
        .map(|s| {
            format!(
                "  {}:{}  region `{}` lma_base = {}",
                s.file, s.line, s.region, s.value
            )
        })
        .collect();
    assert!(
        offenders.is_empty(),
        "a map region named after a real gated cartridge region must take its base from \
         `pins::` (repin regenerates those from the build's own listing), never a hex \
         literal, a typed base goes stale at the next re-layout and no `assert_ne!` \
         probe can notice. If the region is only PARKED here so a neighbouring gate \
         can link, say so with a ``{} `<region>` `` comment on the line or above it:\n{}",
        CARRIER_MARKER,
        offenders.join("\n")
    );
}
