import os
P = "/home/volence/sonic_hacks/.scratch/as-squote/probes"
M = "\tcpu 68000\n"
Z = "\tcpu z80\n"
# A non-identity page with non-repeating targets, and a remap of $23 so a
# second translation of an arithmetic result is visible.
CS = "\tcharset 'A',$11\n\tcharset 'B',$22\n\tcharset 'C',$99\n\tcharset $23,$77\n"
probes = {
 "pw1": M+"\tdc.w ('AB')\n",
 "pw2": M+"\tdc.w ('ABC')\n",
 "pw3": M+"\tdc.w (('AB'))\n",
 "sw1": M+"X equ \"AB\"\n\tdc.w X\n",
 "sw2": M+"X equ 'ABC'\n\tdc.w X\n",
 "sw3": M+"X set 'AB'\n\tdc.w X\n",
 "sw4": M+"X equ 'AB'\nY equ X\n\tdc.w Y\n",
 "sw5": M+"X := 'AB'\n\tdc.w X\n",
 "sw6": M+"X equ 'AB'\n\tdc.l X\n",
 "sw7": M+"X equ 'A'\n\tdc.w X+1\n",
 "fn1": M+"\tdc.w substr('ABC',0,2)\n",
 "fn2": M+"\tdc.w lowstring('AB')\n",
 "fn3": M+"\tdc.w upstring('ab')\n",
 "fn4": M+"\tdc.w strlen('ABC')\n",
 "cc1": M+"\tdc.w 'A'+'B'\n",
 "cc2": M+"\tmove.w #'A'+'B',d0\n",
 "cc3": M+"\tdc.l 'A'+'B'\n",
 "ar1": M+"\tdc.b 'A'+$100\n",
 "ar2": M+"\tdc.b 'AB'+(0-$4142)\n",
 "ar3": M+"\tdc.b 'A'+1\n",
 "ar4": M+"\tdc.w 'A'+1\n",
 "ar5": M+"\tdc.w 'AB'-1\n",
 "ar6": M+"\tdc.l 'ABCD'-1\n",
 "ar7": M+"\tdc.w 'A'*2\n",
 "ar8": M+"\tdc.w 'A'+$100\n",
 "ar9": M+"\tdc.w 'AB'+(1-1)\n",
 "ar10": M+"\tdc.w 'AB'+1-1\n",
 "lw1": M+"\tdc.l 'AB'\n",
 "lw2": M+"\tdc.l ''\n",
 "lw3": M+"\tdc.b '','A'\n",
 "lw4": M+"\tdc.b 'A',''\n",
 "big1": M+"\tdc.l 'ABCDE'>>0\n",
 "big2": M+"\tmove.l #'ABCDE'|0,d0\n",
 "big3": M+"\tmove.l #\"ABCDE\"|0,d0\n",
 "big4": M+"\tdc.l 'ABCDE'-1\n",
 "big5": M+"X equ 'ABCDE'\n\tmove.l #X,d0\n",
 "big6": M+"\tdc.b 'ABCDE'|0\n",
 "cs1": M+CS+"\tdc.b 'ABC'\n",
 "cs2": M+CS+"\tdc.w 'AB'\n",
 "cs3": M+CS+"\tdc.w 'ABC'\n",
 "cs4": M+CS+"\tdc.l 'CAB'\n",
 "cs5": M+CS+"\tmove.l #'CAB',d0\n",
 "cs6": M+CS+"\tdc.b 'AB'+1\n",
 "cs7": M+CS+"\tdc.b 'CBA',0,'B'\n",
 "cs8": M+CS+"X equ 'CA'\n\tcharset\n\tdc.b X\n\tdc.w X\n",
 "cs9": M+"X equ 'CA'\n"+CS+"\tdc.b X\n\tdc.w X\n",
 "cs10": M+CS+"\tdc.b 'A\\x42C'\n",
 "cs11": M+CS+"\tdc.b ''\n",
 "cs12": M+CS+"\tdc.w 'A'+'B'\n",
 "cs13": Z+CS+"\tdb 'CAB'\n\tdw 'CA'\n\tld hl,'BC'\n",
 "cs14": M+CS+"\tdc.b 'AB'+'C'\n",
 "q1": M+"\tdc.b 'A;B'\n",
 "q2": M+"\tdc.b 'A,B',1\n",
 "q3": M+"\tdc.b '\"'\n",
 "q4": M+"\tdc.b \"'\"\n",
 "q5": M+"\tdc.b '\\''\n",
 "q6": M+"\tdc.b 'A''\n",
 "q7": M+"\tdc.b 'AB\n",
 "esc1": M+"\tdc.b '\\x41\\x42'\n",
 "esc2": M+"\tdc.w '\\x41\\x42\\x43'\n",
 "esc3": M+"\tdc.b '\\q'\n",
 "esc4": M+"\tdc.b 'A\\{1+1}B'\n",
 "mw1": M+"m macro a\n\tdc.w a\n\tendm\n\tm 'AB'\n",
 "mw2": M+"m macro a\n\tdc.b a\n\tendm\n\tm 'ABC'\n",
 "irp1": M+"\tirpc c,\"AB\"\n\tdc.w 'c'\n\tendm\n",
 "irp2": M+"\tirpc c,\"AB\"\n\tdc.b 'c'\n\tendm\n",
 "rep1": M+"\trept 2\n\tdc.b 'AB'\n\tendm\n",
 "dup1": M+"\tdc.b [2]'AB'\n",
 "dup2": M+"\tdc.w [2]'AB'\n",
 "cmp1": M+"\tif 'A'<'B'\n\tdc.b 1\n\telse\n\tdc.b 2\n\tendif\n",
 "cmp2": M+"\tif 'AB'<>'AC'\n\tdc.b 1\n\telse\n\tdc.b 2\n\tendif\n",
 "cmp3": M+"\tdc.b 'AB'='AB'\n",
 "z1": Z+"\tdw 'A'\n",
 "z2": Z+"\tdw ''\n",
 "z3": Z+"\tdefw 'AB'\n",
 "z4": Z+"\tdb ''\n",
 "z5": Z+"\tdb 'AB',0,'C'\n",
 "z6": Z+"\tld a,'AB'\n",
 "z7": Z+"\tld hl,'ABC'\n",
 "z8": Z+"\tdw 'AB'-1\n",
 "z9": Z+"\tcp 'A'\n",
 "dcbs": M+"\tdcb.b 2,'A'\n",
 "dcbs2": M+"\tdcb.w 2,'AB'\n",
 "dcbs3": M+"\tdcb.b 2,'AB'\n",
 "lbl1": M+"L:\n\tdc.b 'A'+L\n",
 "lbl2": M+"\tdc.w 'A'+L\nL:\n",
 "lbl3": M+"\tdc.b 'A'+L\nL:\n",
}
for k, v in probes.items():
    open(os.path.join(P, k + ".asm"), "w").write(v)
print(" ".join(probes))
