; ======================================================================
; data/sound/sfx/sfx_33.asm — GENERATED by tools/sfx_transcode.py
; SFX id $33 (Sfx_33)
; Layout: SfxHeader(8) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_33:
    dc.b   $20, $00, $01, $00, $00, $01, $00, $00, $03, $01, $00, $0E, $00, $1A, $E4, $40
    dc.b   $E3, $40, $05, $E3, $43, $05, $E3, $48, $1B, $FF, $04, $C0, $37, $77, $72, $49
    dc.b   $23, $23, $05, $05, $1F, $1F, $1F, $1F, $07, $07, $0A, $0D, $00, $00, $0B, $0B
    dc.b   $1F, $1F, $0F, $0F, $00, $00, $00, $00, $00, $00
Sfx_33_End:

    align 2
