; ======================================================================
; Song_DrumTest.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_DrumTest label (loader adds the base).
; ======================================================================

Song_DrumTest:
    dc.b   $07, $80, $00, $05, $00, $00, $00, $00, $21, $00, $00, $01, $00, $2C, $00, $00
    dc.b   $05, $00, $35, $00, $00, $06, $00, $40, $00, $00, $0A, $00, $49, $00, $00, $00
    dc.b   $00, $E1, $01, $E0, $5F, $1E, $EE, $B1, $B5, $B8, $B5, $EF, $E1, $00, $E0, $55
    dc.b   $3C, $EE, $A5, $AC, $EF, $E1, $02, $E0, $50, $1E, $EE, $BD, $C1, $C4, $C1, $EF
    dc.b   $E0, $30, $1E, $EE, $B5, $B8, $B5, $B1, $EF, $3C, $EE, $E2, $02, $80, $E2, $03
    dc.b   $80, $EF
Song_DrumTest_End:

    align 2
