	cpu 68000
	move.b T(pc,d3.w),d5
	move.w T(pc,d3.l),d5
	move.l T(pc,a3.w),d5
	move.w T(pc,a3.l),(a5)
	move.l T(pc,d6.w),$1234(a5)
	movea.w T(pc,d3.w),a5
	movea.l T(pc,a2.l),a5
	move.w T(pc,d3.w),a5
	add.b T(pc,d3.w),d5
	add.w T(pc,d3.l),d5
	add.l T(pc,a3.w),d5
	adda.w T(pc,d3.w),a5
	adda.l T(pc,d3.l),a5
	sub.w T(pc,d3.w),d5
	suba.l T(pc,a4.w),a5
	and.w T(pc,d3.w),d5
	or.l T(pc,d3.l),d5
	cmp.b T(pc,d3.w),d5
	cmp.w T(pc,a3.l),d5
	cmpa.w T(pc,d3.w),a5
	cmpa.l T(pc,d3.w),a5
	muls.w T(pc,d3.w),d5
	mulu.w T(pc,d3.l),d5
	divs.w T(pc,a3.w),d5
	divu.w T(pc,d3.w),d5
	btst d5,T(pc,d3.w)
	btst #3,T(pc,d3.l)
T: dc.w 1
	lea T(pc,d3.w),a5
	lea T(pc,a3.l),a5
	pea T(pc,d3.w)
	jmp T(pc,d3.w)
	jsr T(pc,a3.l)
	movem.w T(pc,d0.w),d2-d3
	movem.l T(pc,d3.l),d0-d2/a4
	movem.w T(pc,a3.w),a0/d6
	movem.l T(pc,a2.l),d0-d7/a0-a6
	move.w T(pc,d3.w),ccr
	move.w T(pc,d3.w),sr
	move T(pc,d3.w),ccr
	move.w T(pc,d3),d5
	move.w T(PC,D3.W),d5
	move.w T(Pc,d3.W),d5
	move.w (T,pc,d3.w),d5
	move.w (T,PC,a3.L),d5
	move.w T(pc,sp.w),d5
	move.w T(pc,a7.l),d5
	movem.w (T,pc,d3.w),d2/d4
	movem.w T(pc,d3),d2/d4
