S=/home/volence/sonic_hacks/.cargo-s1baseline/release/sigil
run(){ printf '%b' "$2" > p.asm; out=$($S p.asm --hex 2>&1); ec=$?; printf '%-22s exit=%s  %s\n' "$1" "$ec" "$(echo "$out"|tr '\n' '|')"; }
run "save/restore"      '\tcpu 68000\n\tsave\n\tcpu z80\n\tnop\n\trestore\n\tdc.b $AA\n'
run "phase/dephase"     '\tcpu 68000\n\tphase $8000\nL:\tdc.b 1\n\tdephase\n\tdc.l L\n'
run "padding off"       '\tcpu 68000\n\tpadding off\n\tdc.b 1\n\teven\n'
run "supmode on"        '\tcpu 68000\n\tsupmode on\n\tmove.w sr,d0\n'
run "listing off"       '\tcpu 68000\n\tlisting off\n\tdc.b 1\n'
run "page 0"            '\tcpu 68000\n\tpage 0\n\tdc.b 1\n'
run "dcb.b"             '\tcpu 68000\n\tdcb.b 4,$FF\n'
run "eval (label form)" '\tcpu 68000\nX eval 5\n\tdc.b X\n'
run "eval (2-arg form)" '\tcpu 68000\n\teval X,5\n\tdc.b X\n'
run "set 2-arg form"    '\tcpu 68000\n\tset X,5\n\tdc.b X\n'
run "enum/nextenum"     '\tcpu 68000\n\tenum a=1,b\n\tnextenum c\n\tdc.b a,b,c\n'
run "charset"           '\tcpu 68000\n\tcharset "A","\\$41"\n\tdc.b "A"\n'
run "irp"               '\tcpu 68000\n\tirp x,1,2,3\n\tdc.b x\n\tendm\n'
run "irpc"              '\tcpu 68000\n\tirpc c,"abc"\n\tdc.b 1\n\tendm\n'
run "switch int"        '\tcpu 68000\nV = 1\n\tswitch V\n\tcase 1\n\tdc.b $11\n\tcase 2\n\tdc.b $22\n\tendcase\n'
run "bchg"              '\tcpu 68000\n\tbchg #1,d0\n'
run "exg"               '\tcpu 68000\n\texg d0,d1\n'
run "roxl"              '\tcpu 68000\n\troxl.w #1,d0\n'
run "move d6,ccr"       '\tcpu 68000\n\tmove.w d6,ccr\n'
run "usp"               '\tcpu 68000\n\tmove.l usp,a0\n'
run "struct DOTS"       '\tcpu 68000\nS struct DOTS\na ds.b 1\nb ds.w 1\nS endstruct\n\tdc.b S.b, S.len\n'
run "multi-char lit"    '\tcpu 68000\n\tmove.w #"SW",d0\n'
run "[n]v dc repeat"    '\tcpu 68000\n\tdc.b [4]$FF\n'
run "macro default arg" '\tcpu 68000\nm macro a,b=7\n\tdc.b a,b\n\tendm\n\tm 1\n'
run "warning directive" '\tcpu 68000\n\twarning "hi"\n\tdc.b 1\n'
run "message directive" '\tcpu 68000\n\tmessage "hi"\n\tdc.b 1\n'
run "interp \\{}"       '\tcpu 68000\nV = 5\n\tmessage "v=\\{V}"\n\tdc.b 1\n'
run "END stops asm"     '\tcpu 68000\n\tdc.b 1\n\tEND\n\tzzz_after_end\n'
